[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", default-features = false, features = [] }
cxx-build = "1.0"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "^2.0.0-beta.17", features = ["macos-private-api"] }
window-vibrancy = "0.5.0"
tauri-plugin-decorum = "0.1.3"
windows = "0.56.0"
cxx = "1.0.119"
enigo = "0.2.0"
anyhow = "1.0.82"
